apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
data:
  SPEEDTEST_PORT: {{ .Values.speedTestPort | quote }}
  SPEEDTEST_SERVER: {{ .Values.speedTestServer | quote }}
  SPEEDTEST_TIMEOUT: {{ .Values.speedTestTimeout | quote }}
