{{- if .Values.speedTestDaemonSet }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
spec:
{{- include "pod_spec" . | nindent 2 }}
{{- end }}
