{{- if and .Values.PrometheusMonitor.enabled ( eq .Values.PrometheusMonitor.type "pod" ) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  {{- with .Values.PrometheusMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "speedtest-exporter.fullname" . }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
    {{- with .Values.PrometheusMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "speedtest-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    interval: {{ .Values.PrometheusMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.PrometheusMonitor.scrapeTimeout }}
    {{- with .Values.PrometheusMonitor.additionalConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
