apiVersion: v1
kind: Service
metadata:
  name: {{ include "speedtest-exporter.fullname" . }}
  labels:
    {{- include "speedtest-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.speedTestPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "speedtest-exporter.selectorLabels" . | nindent 4 }}
