replicaCount: 1

image:
  repository: ghcr.io/miguelndecarvalho/speedtest-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

speedTestServer: "" 
speedTestPort: 9798
speedTestTimeout: 90

speedTestDaemonSet: false

PrometheusMonitor:
  enabled: false
  type: service
  scrapeInterval: 10m
  scrapeTimeout: 91s
  annotations: {}
  additionalLabels: {}
  additionalConfig: {}

grafanaNamespace: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
nodeSelector: {}

tolerations: []

affinity: {}
